### ISSUE TITLE
Proposal for a cleaner API

### ISSUE THREAD

**Issue by rstacruz** [gsmendoza/test_changes#4]
I find that .test_changes.yaml is a little arbitrary:
- It ends in `.yaml` instead of '.yml' (as I'd expect with '.travis.yml').
- It doesn't follow the same format as, say, `.rspec`.
- It's unclear how to override parameters in the command line with whatever's defined in .yml.

With that said, I propose a better API for test_changes. Like rspec, everything configurable should be available as command-line switches.

``` sh
test-changes [-r,--runner RUNNER] [-p,--pattern /from/to/] [--pattern ...] [-c,--commit HEAD] [-- passthru parameters]
```

The parameters are passed through `--`, which is the same as what you'd expect with ssh.

``` sh
ssh rsc@localhost -- cat /etc/passwd
test-changes -r rspec -- --fail-fast
```

And to configure it, just create a `.test_changes` file in your project (much like .rspec) with the command line switches. Other test runners follow this convention, like [mocha.js](http://mochajs.org/).

``` sh
# .test_changes
--runner "bundle exec rspec"
--pattern "#^app/(models)/(.+).rb#spec/\1/\2_spec.rb#"
--pattern "#^app/(controller|helper|view)s/(.+).rb#spec/controllers/\2_\1_spec.rb#"
```

The pattern format is pattered after `ctags`, which looks like this:

``` sh
# ~/.ctags
--regex-css=/^([A-Za-z0-9_-]+)\(/\1/m,mixin,mixins/
```

The `/` delimiter can be any character, much like sed or vim or anything else, so I used `#` in the example above.

**Comment by gsmendoza** [comment]
Sounds good @rstacruz  :) I'm not sure if this will allow the test tool arguments to be passed to `test_changes` e.g. `test_changes --format=documentation HEAD^` API. If it doesn't, it would be nice if we can keep the API as succinct as possible. Maybe `test_changes -o "--format=documentation" HEAD^`?

I can start working on this next week. If you like to work on this, please go ahead :) I've added you as a collaborator to the repo. Please submit a pull request for any feature you'd like to add.

**Comment by rstacruz** [comment]
`-o "--format=documentation"` is ambiguous because it's unclear how to do multiple arguments with spaces, say, how would you invoke `mocha --grep "user model"`?

if we're to go by unix convention, it should be passable by delimiting your arguments with `--` - a marker to stop parsing options arguments. that is:

``` sh
test_changes -r mocha -- -r babel/require --grep "user model"
```

this is something seen in other CLI utilities:

``` sh
ssh rsc@localhost -- cat /etc/passwd
```

if we're to use something like [slop](http://rubygems.org/gems/slop), this is something it [naturally supports](https://github.com/leejarvis/slop/blob/1a075c05d38be0df849119530378043994c05c91/test/parser_test.rb#L13).

**Comment by gsmendoza** [comment]
> `--pattern "#^app/(controller|helper|view)s/(.+).rb#spec/controllers/\2_\1_spec.rb#"`

One thing that makes this format less enticing is that it doesn't support one pattern to many specs as well. For example, I have these finding patterns right now on my configuration:

``` yaml
^app/services/order_sale.rb:
- spec/services/order_redemption_spec.rb
- spec/services/order_purchase_spec.rb
- spec/acceptance/order_purchase_spec.rb
```

Any suggestions?

**Comment by rstacruz** [comment]
looks like a special case unfortunately and no one size would fit all.

**Comment by rstacruz** [comment]
...but app/X/Y.rb would be nice to translate to spec/X/Y_spec.rb to account for services :)

**Comment by rstacruz** [comment]
now that i think about it it might be cool to reconsider this too, say some projects would have both cuke and rspec tests... dont know how to account for that elegantly in this scheme.
