### ISSUE TITLE
As the owner, I want Travis to run RuboCop

### ISSUE THREAD

**Issue by gsmendoza** [gsmendoza/test_changes#6]
So that new contributors will become aware of the project's style guide.

**Comment by rstacruz** [comment]
Up to you how you wanna do this. Maybe:

``` yml
# .travis.yml
script:
  - bundle exec rspec
  - bundle exec rubocop
```

...or create a Rake task to invoke both.

**Comment by gsmendoza** [comment]
I think that should be enough. I don't think the rake task would be useful elsewhere.

**Comment by gsmendoza** [comment]
Added in https://github.com/gsmendoza/test_changes/commit/9291f459e8cd8c882d77d591f6463ff25c319613
