### ISSUE TITLE
As the owner, I want a Travis badge on the README

### ISSUE THREAD

**Issue by gsmendoza** [gsmendoza/test_changes#7]
So that users will see the status of the gem's build.

**Comment by rstacruz** [comment]
did you really have to write it in story form? lol

**Comment by rstacruz** [comment]
https://github.com/gsmendoza/test_changes/commit/7c5da8316f62cbf3cda3a931009719fbe597fede

**Comment by gsmendoza** [comment]
Hehe. Yeah, I did :)
